前面學過 sum()、mean()、count()，這些方法可以直接計算整份資料。例如：


```
df["金額"].sum() # 計算所有交易的總金額
```

但實際分析時，我們通常不只想知道「全部花了多少錢？」，更常遇到的是「餐飲花多少？交通花多少？娛樂又花多少？」

groupby() 的概念其實很生活化。假設老師要計算每組學生的平均成績，可以先按照「組別」把學生分桌，再分別計算每桌的平均分數。

> 用班級生活比喻：`groupby`先依組別把同學分桌，再計算每桌人數或平均成績。

In [2]:
import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)
df

   交易編號  類別 付款方式   金額
0  T001  餐飲   現金  120
1  T002  交通  悠遊卡   50
2  T003  餐飲  信用卡  280
3  T004  娛樂  信用卡  450
4  T005  交通  悠遊卡   35
5  T006  餐飲   現金   90
6  T007  娛樂  信用卡  600
7  T008  交通  悠遊卡   60
8  T009  餐飲  信用卡  200
9  T010  娛樂   現金  300

### sum()：每組總和

In [6]:
### 計算各類別總金額
category_total = df.groupby("類別")["金額"].sum() # 按照「類別」將資料分組，再把每個類別的「金額」加總起來。
category_total

類別
交通     145
娛樂    1350
餐飲     690
Name: 金額, dtype: int64

### mean()：每組平均

In [7]:
import pandas as pd

### 計算各類別平均消費
result = df.groupby("類別")["金額"].mean()
result

類別
交通     48.333333
娛樂    450.000000
餐飲    172.500000
Name: 金額, dtype: float64

### max()：每組最大值

In [8]:
import pandas as pd

df = pd.DataFrame(data)

### 找出各類別最高單筆消費
result = df.groupby("類別")["金額"].max()
result

類別
交通     60
娛樂    600
餐飲    280
Name: 金額, dtype: int64

### min()：每組最小值

In [9]:
import pandas as pd

### 找出各類別最低單筆消費
result = df.groupby("類別")["金額"].min()
result

類別
交通     35
娛樂    300
餐飲     90
Name: 金額, dtype: int64

### size()：每組有幾筆資料

size()計算「每組有幾列」，會計算缺失值。

In [10]:
import pandas as pd

### 計算各類別交易筆數
result = df.groupby("類別").size()
result

類別
交通    3
娛樂    3
餐飲    4
dtype: int64

### count()：計算非缺失值數量

count()計算「指定欄位有幾個非缺失值」，不會計算缺失值。

In [12]:
import pandas as pd


### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 計算每組實際列數
print(df.groupby("類別").size())

### 計算金額欄位的非缺失值數量
print(df.groupby("類別")["金額"].count())

類別
交通    3
娛樂    3
餐飲    4
dtype: int64
類別
交通    3
娛樂    3
餐飲    4
Name: 金額, dtype: int64

### agg()：Aggregate(聚合)的縮寫


```py
### 一次計算多項統計資料
summary = df.groupby("類別")["金額"].agg([
    "count",
    "sum",
    "mean",
    "max",
    "min"
])

print(summary)
```

In [13]:
### 一次計算多個統計結果
import pandas as pd

### 一次計算多項統計資料
summary = df.groupby("類別")["金額"].agg([
    "count",
    "sum",
    "mean",
    "max",
    "min"
])

summary

    count   sum        mean  max  min
類別
交通      3   145   48.333333   60   35
娛樂      3  1350  450.000000  600  300
餐飲      4   690  172.500000  280   90

In [14]:
### 自己命名統計欄位

import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 分組並建立統計摘要
summary = (
    df.groupby(
        "類別",
        as_index=False
    )
    .agg(
        交易筆數=("交易編號", "count"),
        總金額=("金額", "sum"),
        平均金額=("金額", "mean"),
        最高金額=("金額", "max"),
        最低金額=("金額", "min")
    )
)

summary

   類別  交易筆數   總金額        平均金額  最高金額  最低金額
0  交通     3   145   48.333333    60    35
1  娛樂     3  1350  450.000000   600   300
2  餐飲     4   690  172.500000   280    90

### as_index=False：類別也視為一列資料

In [18]:
### 這樣寫：
import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)
summary = df.groupby("類別")["金額"].sum()

summary

類別
交通     145
娛樂    1350
餐飲     690
Name: 金額, dtype: int64

In [19]:
### 但很多時候我們希望「類別」繼續是一個普通欄位。這時可以：
import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)
summary = df.groupby("類別", as_index=False)["金額"].sum()

summary

   類別    金額
0  交通   145
1  娛樂  1350
2  餐飲   690

### 練習：飲料店銷售分析

飲料店老闆想知道不同飲料類別的銷售表現，請使用 `groupby()` 完成分析。

In [ ]:
import pandas as pd


### 建立飲料銷售資料
data = {
    "訂單編號": ["D001", "D002", "D003", "D004", "D005", "D006", "D007", "D008", "D009", "D010"],
    "類別": ["茶類", "奶茶", "茶類", "咖啡", "奶茶", "咖啡", "茶類", "奶茶", "咖啡", "茶類"],
    "付款方式": ["現金", "LINE Pay", "信用卡", "現金", "LINE Pay", "信用卡", "現金", "信用卡", "LINE Pay", "現金"],
    "金額": [40, 65, 50, 90, 75, 120, 35, 80, 100, 55]
}

df = pd.DataFrame(data)
df

請完成以下任務：

1. 按照 `"類別"` 分組，計算每個類別的**總銷售金額**。
2. 計算每個類別的**平均消費金額**。
3. 找出每個類別的**最高單筆消費金額**。
4. 找出每個類別的**最低單筆消費金額**。
5. 使用 `size()` 計算每個類別有**幾筆訂單**。
6. 使用 `count()` 計算每個類別 `"金額"` 欄位有**幾筆非缺失資料**。
7. 使用 `agg()` 一次計算 `"金額"` 的 `count`、`sum`、`mean`、`max`、`min`。
8. 使用 `as_index=False`，讓 `"類別"` 保持為普通欄位。

### 練習：健身房會員消費分析

健身房提供不同類型的課程，現在想知道各課程的消費狀況，請整理出一份統計摘要。

In [ ]:
import pandas as pd


### 建立健身房消費資料
data = {
    "交易編號": ["G001", "G002", "G003", "G004", "G005", "G006", "G007", "G008", "G009", "G010"],
    "課程": ["重訓", "瑜珈", "有氧", "重訓", "瑜珈", "有氧", "重訓", "瑜珈", "有氧", "重訓"],
    "會員": ["小明", "小華", "小美", "阿哲", "小安", "小宇", "小杰", "小婷", "小豪", "小芸"],
    "消費金額": [800, 600, 500, 1200, 750, 650, 1000, 550, 700, 900]
}

df = pd.DataFrame(data)
df

請完成以下任務：

1. 按照 `"課程"` 分組，計算各課程的**總消費金額**。
2. 計算各課程的**平均消費金額**。
3. 找出各課程的**最高消費金額**。
4. 找出各課程的**最低消費金額**。
5. 計算每種課程共有**幾筆交易紀錄**。
6. 使用 `agg()` 一次取得各課程的 `"消費金額"`：`count`、`sum`、`mean`、`max`、`min`。
7. 改用**自己命名統計欄位**的方式，建立下面這份摘要：

```text
課程
交易筆數
總消費
平均消費
最高消費
最低消費
```

8. 第 7 題搭配 `as_index=False`，讓 `"課程"` 保持為普通欄位，而不是 index。
9. 觀察最後的統計結果，回答：**哪一種課程的總消費金額最高？**