In [1]:
### 建立資料
import pandas as pd

df = pd.DataFrame({
    "訂單編號": ["A001", "A002", "A003", "A004", "A005"],
    "餐點": ["牛肉麵", "雞腿飯", "火鍋", "水餃", "咖哩飯"],
    "餐點金額": [180, 120, 350, 90, 250],
    "狀態": ["完成", "完成", "未完成", "取消", "完成"],
    "付款方式": ["現金", "信用卡", "信用卡", "現金", "LINE Pay"]
})

df

   訂單編號   餐點  餐點金額   狀態      付款方式
0  A001  牛肉麵   180   完成        現金
1  A002  雞腿飯   120   完成       信用卡
2  A003   火鍋   350  未完成       信用卡
3  A004   水餃    90   取消        現金
4  A005  咖哩飯   250   完成  LINE Pay

### 選欄位：「我只想看哪些資料？」

In [7]:
result_Series = df["餐點金額"] 
result_Series

0    180
1    120
2    350
3     90
4    250
Name: 餐點金額, dtype: int64

In [6]:
result_DataFrame = df[["訂單編號", "餐點金額"]]
result_DataFrame

   訂單編號  餐點金額
0  A001   180
1  A002   120
2  A003   350
3  A004    90
4  A005   250

### loc 與 iloc：「我要指定哪些位置的資料？」

- df.loc[我要哪些列, 我要哪些欄]`：看標籤、名稱、條件
- iloc：看第幾列、第幾欄

> - loc → label(標籤) → 看「名字」
> - iloc → integer location(整數位置) → 看「第幾個位置」

In [9]:
result = df.loc[df["餐點金額"] >= 250, ["訂單編號", "餐點金額"]]
result

   訂單編號  餐點金額
2  A003   350
4  A005   250

In [10]:
result = df.iloc[:3, :2] # 我要前 3 筆資料，而且只看前 2 欄。
result

   訂單編號   餐點
0  A001  牛肉麵
1  A002  雞腿飯
2  A003   火鍋

### 布林篩選：「哪些資料符合我的條件？」

In [11]:
# 情境：餐廳想找出所有「已完成，而且餐點金額 >= 150」的訂單。
# 可以先拆成兩個條件：
# 1. df["狀態"] == "完成"
# 2. df["餐點金額"] >= 150
# 3. 再把兩個條件使用 & 結合

result = df[
    (df["狀態"] == "完成") &
    (df["餐點金額"] >= 150)
]

result

   訂單編號   餐點  餐點金額  狀態      付款方式
0  A001  牛肉麵   180  完成        現金
4  A005  咖哩飯   250  完成  LINE Pay

### Problem. 咖啡店訂單篩選

咖啡店想整理今天的訂單，請使用 Pandas 完成指定的資料選取與篩選。

In [1]:
import pandas as pd


### 建立資料
df = pd.DataFrame({
    "訂單編號": ["C001", "C002", "C003", "C004", "C005", "C006"],
    "飲品": ["美式咖啡", "拿鐵", "紅茶", "卡布奇諾", "拿鐵", "美式咖啡"],
    "金額": [80, 130, 60, 150, 130, 80],
    "狀態": ["完成", "完成", "取消", "製作中", "完成", "完成"],
    "付款方式": ["現金", "信用卡", "現金", "LINE Pay", "LINE Pay", "信用卡"]
})

df

   訂單編號    飲品   金額   狀態      付款方式
0  C001  美式咖啡   80   完成        現金
1  C002    拿鐵  130   完成       信用卡
2  C003    紅茶   60   取消        現金
3  C004  卡布奇諾  150  製作中  LINE Pay
4  C005    拿鐵  130   完成  LINE Pay
5  C006  美式咖啡   80   完成       信用卡

請完成以下任務：

1. 只選取 `"飲品"` 欄位，結果使用 `Series` 顯示。
2. 同時選取 `"訂單編號"`、`"飲品"`、`"金額"` 三個欄位。
3. 使用 `iloc` 取得**前 3 筆資料的前 2 個欄位**。
4. 使用 `loc` 找出 `"金額"` 大於等於 130 元的訂單，只顯示 `"訂單編號"`、`"飲品"`、`"金額"`。
5. 找出所有 `"狀態"` 為 `"完成"` 的訂單。
6. 找出所有 `"付款方式"` 為 `"信用卡"` 的訂單。
7. 找出**狀態為 `"完成"`，而且金額大於等於 100 元**的訂單。

### Problem. 電影院售票紀錄篩選

電影院想分析今天的售票狀況，請從下面的資料中找出符合條件的紀錄。

In [ ]:
import pandas as pd

### 建立資料
df = pd.DataFrame({
    "票號": ["T001", "T002", "T003", "T004", "T005", "T006", "T007"],
    "電影": ["星際冒險", "城市英雄", "星際冒險", "恐龍世界", "城市英雄", "恐龍世界", "星際冒險"],
    "票價": [320, 280, 320, 350, 280, 350, 320],
    "票種": ["全票", "學生票", "全票", "全票", "學生票", "全票", "學生票"],
    "狀態": ["已入場", "已入場", "未入場", "已入場", "取消", "未入場", "已入場"]
})
df

     票號    電影   票價   票種   狀態
0  T001  星際冒險  320   全票  已入場
1  T002  城市英雄  280  學生票  已入場
2  T003  星際冒險  320   全票  未入場
3  T004  恐龍世界  350   全票  已入場
4  T005  城市英雄  280  學生票   取消
5  T006  恐龍世界  350   全票  未入場
6  T007  星際冒險  320  學生票  已入場

請完成以下任務：

1. 只選取 `"電影"` 欄位。
2. 同時選取 `"票號"`、`"電影"`、`"票價"` 三個欄位。
3. 使用 `iloc` 取得**前 4 筆資料，而且只顯示前 3 個欄位**。
4. 使用 `loc` 找出 `"票價"` 大於等於 320 元的資料，只顯示 `"電影"`、`"票價"`。
5. 找出 `"票種"` 為 `"學生票"` 的所有資料。
6. 找出 `"狀態"` 為 `"已入場"` 的所有資料。
7. 找出**票種為 `"學生票"`，而且狀態為 `"已入場"`**的資料。
8. 找出**票價大於等於 300 元，而且狀態為 `"未入場"`**的資料。
9. 綜合題：找出**票價大於等於 300 元，而且狀態為 `"已入場"`**的紀錄，最後只顯示 `"票號"`、`"電影"`、`"票價"` 三個欄位。